# This workflow will execute the manybody test on push and pull requests

name: Many-Body Groundstate Short Test

# Run on push, pull request and manual execution
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
      # Cache so dependencies only need to be installed once
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .
        
    - name: Verify installation
      run: |
        pip list
    
    - name: Run TestShort with pytest 
      run: |
        pytest tests/test_manybody.py::TestShort
